name: demo-ts

services:
  backend-ts-migrations:
    build:
      dockerfile: ./Dockerfile.dev
    command: npm run knex -- migrate:latest
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_NAME: postgres-ts
      DB_PASSWORD: postgres
      # DB_DEBUG: 1
      # DB_SSL: postgres # Production
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
