# Build
FROM localhost/microservice-sdk-build as build
ENV NODE_ENV=development
WORKDIR /workspace/app/backend-ts
COPY package.json tsconfig.json .
RUN npm install

# Run
FROM localhost/microservice-sdk-build
WORKDIR /workspace/app/backend-ts
COPY --from=build /workspace/app/backend-ts /workspace/app/backend-ts
COPY /src /workspace/app/backend-ts/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/backend-ts" ]
