name: demo-ts

services:
  # Dapr placement service
  placement:
    image: "docker.io/daprio/dapr"
    command: ["./placement", "-port", "50005"]
    ports:
      - "50005:50005"
    networks:
      - dapr-net
  # Dapr state and pubsub provider
  redis:
    image: "docker.io/redis:7-alpine"
    restart: always
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no", "--maxmemory", "500mb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - dapr-net
  # Dapr metrics provider
  zipkin:
    image: "docker.io/openzipkin/zipkin"
    ports:
      - "9411:9411"
    environment:
      - JAVA_OPTS=-XX:UseSVE=0
    networks:
      - dapr-net
  # Dapr dashboard
  dapr-dashboard:
    image: "docker.io/daprio/dashboard:latest"
    command: [ "--docker-compose=true",
      "--components-path=/home/nonroot/components",
      "--config-path=/home/nonroot/config",
      "--docker-compose-path=/home/nonroot/docker-compose.yaml" ]
    ports:
      - "8080:8080"
    volumes:
      - "./components/:/home/nonroot/components"
      - "./config/:/home/nonroot/config"
      # - "../../app/:/app/app"
      - ./docker-compose.yaml:/home/nonroot/docker-compose.yaml
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
