"""empty message

Revision ID: 124967b49088
Revises: 5eaba0c3f6e7
Create Date: 2025-02-28 17:10:17.137381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124967b49088'
down_revision = '5eaba0c3f6e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_column('due_at')

    # ### end Alembic commands ###
