# Build
FROM localhost/microservice-build as build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json next.config.ts postcss.config.mjs tsconfig.json eslint.config.mjs .
RUN npm install
WORKDIR /app/public
COPY public .

# Run
FROM localhost/microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "npm", "run", "dev" ]
