# Build
FROM localhost/microservice-build as build

WORKDIR /app
COPY package.json package-lock.json .
RUN npm install

# Run
FROM localhost/microservice-build

WORKDIR /app
COPY --from=build /app /app
EXPOSE 3000
CMD [ "npm", "run", "start" ]
