# Build
FROM localhost/microservice-sdk-build as build
ENV NODE_ENV=development
WORKDIR /workspace/app/api-gateway
COPY package.json tsconfig.json ./
RUN npm install

# Run
FROM localhost/microservice-sdk-build
WORKDIR /workspace/app/api-gateway
COPY --from=build /workspace/app/api-gateway /workspace/app/api-gateway
COPY /src /workspace/app/api-gateway/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/api-gateway" ]
