# https://docs.dapr.io/getting-started/tutorials/get-started-component/#step-2-create-a-secret-store-dapr-component
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsFile
      value: dev-secrets.json #path to secrets file
    - name: nestedSeparator
      value: ':'
    - name: multiValued
      value: 'true'
