# Build
FROM localhost/microservice-sdk-build as build
ENV NODE_ENV=development
WORKDIR /workspace/app/<%= name %>
COPY package.json package-lock.json tsconfig.json .
RUN npm install

# Run
FROM localhost/microservice-sdk-build
WORKDIR /workspace/app/<%= name %>
COPY --from=build /workspace/app/<%= name %> /workspace/app/<%= name %>
COPY /src /workspace/app/<%= name %>/src
EXPOSE 3001
WORKDIR /workspace
CMD [ "npm", "run", "dev", "-w", "app/<%= name %>" ]
