# Build
FROM localhost/microservice-build as build
ENV NODE_ENV=development
WORKDIR /app
COPY package.json package-lock.json tsconfig.json .
RUN npm install

# Run
FROM localhost/microservice-build
WORKDIR /app
COPY --from=build /app /app
COPY /src /app/src
EXPOSE 3001
CMD [ "npm", "run", "dev" ]
