FROM mcr.microsoft.com/dotnet/sdk:9.0

COPY zscaler_chain_root-int.pem /usr/local/share/ca-certificates/zscaler.crt
RUN chmod 644 /usr/local/share/ca-certificates/zscaler.crt && update-ca-certificates
