#Build stage
FROM localhost/microservice-java-build AS BUILD
WORKDIR /app
COPY . .
RUN gradle build -x test

# Run
FROM localhost/microservice-java-build
WORKDIR /app
COPY --from=BUILD /app .

EXPOSE 3004
CMD ["gradle", "bootRun"]
