#Build stage
FROM localhost/microservice-java-build AS BUILD
WORKDIR /app
COPY . .
RUN gradle build -x test

# Run
FROM localhost/microservice-java-build
WORKDIR /app
COPY --from=BUILD /app .
COPY ./src /app/src

RUN chmod +x start.sh

EXPOSE 3004
# script which watches source file changes in background and executes bootRun
CMD ["sh", "start.sh", "development"]
