# Run
FROM localhost/microservice-python-build
WORKDIR /app
COPY requirements.txt /app
RUN pip install -r requirements.txt
COPY /src /app/src
COPY /migrations /app/migrations
RUN opentelemetry-bootstrap -a install
EXPOSE 3003
CMD [ "flask", "--app", "src/app", "run", "-p", "3003" ]
