FROM localhost/microservice-dotnet-build as build
WORKDIR /App
COPY . ./
RUN dotnet restore

FROM localhost/microservice-dotnet-build
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /App
COPY --from=build /App .
RUN dotnet build
EXPOSE 3002
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile"]
