FROM localhost/microservice-dotnet-build as build
WORKDIR /App
# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0
ENV ASPNETCORE_ENVIRONMENT=Development
WORKDIR /App
COPY --from=build /App/out .
ENTRYPOINT ["dotnet", "backend-dotnet.dll"]
