server:
  port: 3004
spring:
  profiles:
    default: localhost
  application:
    name: backend-spring
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migrations
  jackson:
    serialization:
      indent_output: true
otel:
  service:
    name: backend-spring
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  instrumentation:
    spring-webmvc:
      enabled: true
    spring-webflux:
      enabled: true
  resource:
    attributes: deployment.environment=development
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
