spring:
  main:
    banner-mode: console
  devtools:
    restart:
      enabled: 'true'
  application:
    admin:
      enabled: true
  datasource:
    url: ${DB_URI:jdbc:postgresql://localhost:5432/postgres-spring}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
otel:
  exporter:
    otlp:
      endpoint: ${OTEL_ENDPOINT:http://localhost:4318}
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    metrics:
      export:
        url: ${OTEL_METRICS_URL:http://localhost:4318/v1/metrics}
