name: demo-ts

services:
  ############################
  # React frontend
  ############################
  web-react:
    labels:
      - "sos.service-type=microservice"
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - /app/node_modules # Persist docker containers modules so that localhost are not used
      - ./src:/app/src
    restart: on-failure:3
    networks:
      - dapr-net

networks:
  dapr-net: # here we set the network name
    driver: bridge
