name: demo-ts

services:
  ############################
  # backend app + Dapr sidecar
  ############################
  <%= name %>:
    labels:
      - "sos.service-type=microservice"
    build:
      dockerfile: ./Dockerfile.dev
    ports:
      - "3000:3000"
    command: npm run dev
    environment:
      DAPR_HOST: 127.0.0.1
      DAPR_PORT: 3500
      OTLP_ENDPOINT: http://grafana-otel:4318
      JWT_SECRET_KEY: secret
    volumes:
      - /workspace/app/<%= name %>/node_modules # Persist docker containers modules so that localhost are not used
      - ./src:/workspace/app/<%= name %>/src
    depends_on:
      - redis
      - placement
      - zipkin
      - postgres
    restart: on-failure:3
    networks:
      - dapr-net
  <%= name %>-dapr:
    labels:
      - "sos.service-type=microservice"
      - "dapr.io/enabled=true"  # Enable Dapr for this service
      - "dapr.io/config=configstore"
    image: "docker.io/daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "<%= name %>",
      "--app-port", "3000",
      "--config", "/configuration/config.yaml",
      "--dapr-http-port", "3500",
      "--enable-api-logging",
      "--enable-profiling",
      "--log-as-json", "true",
      "--placement-host-address", "placement:50005",
      "--profile-port", "7777",
      "--resources-path", "/components"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/config/:/configuration"
    depends_on:
      - <%= name %>
    network_mode: "service:<%= name %>"

networks:
  dapr-net: # here we set the network name
    driver: bridge
